### PR TITLE
Propose GPLv3 license

### PR DESCRIPTION
**Pull request by Deweh**
~~Propose MIT license~~

Updated to GPLv3 as that seems to be the more preferred license.

### CODE REVIEW

**Comment by ThirdEyeSqueegee** [comment]
I vote GPLv3

**Comment by Deweh** [comment]
I'm prefer GPLv3 as well. Just wasn't sure if other contributors wanted to go the copyleft route.

**Comment by GELUXRUM** [comment]
GPLv3

**Comment by Nightfallstorm** [comment]
GPLv3 all the way

**Comment by Deweh** [comment]
I've updated the proposal to GPLv3.

**Comment by AnyOldName3** [comment]
You *can't* use the GPL3. No one would legally be able to load anything into the same process as the game. You want a GPL3 variant with the exception detailed here https://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs to permit linking with the game's executable. You'll also probably want to word it such that future Bethesda Game Studios games are allowed, otherwise people won't be able to reuse anything when TES6 etc. are released.

All that said, it *might* be preferable to instead use the *L*GPL3 (with the same exemption if it statically links with anything from the game, otherwise it isn't necessary). That would allow plugins that only dynamically link with things from this repo to use whatever licence they want, whereas with the modified GPL3, they'd all have to use the same modified GPL3 licence (and wouldn't be allowed to have any GPL dependencies that didn't also have the same exception).

**Comment by jpstewart** [comment]
I would recommend Apache License 2.0. It's permissive, so no impact on what end users can do or has any implications on linkage with the game or SFSE. It has the backing of a major organization, was crafted by actual lawyers, and covers modern issues of both copyright and patent law.

I don't see any value in a non-permissive license as there is very little novel code, and representations of SF structs or memory locations of functions are not copyrightable.

**Comment by Deweh** [comment]
I'm going to go ahead and close this PR. alandtse said he'll submit a PR later with all the specifics sorted out.

**Pull request closed without merging**
