### PR TITLE
chore: revert #9 .clang-format changes

### PR DESCRIPTION
**Pull request by gottyduke**
This PR reverts the changes introduced in #9 , and keeps the `.clang-format` file the same as the version used in various past CLib projects and plugins.

### CODE REVIEW

**Comment by ThirdEyeSqueegee** [comment]
Remove the deprecated rules at least, unless we're gonna use clang-format v10 or something

**Comment by gottyduke** [comment]
> Remove the deprecated rules at least, unless we're gonna use clang-format v10 or something

Good call, changed the .clang-format to v10 now.

**Comment by gottyduke** [comment]
> > Remove the deprecated rules at least, unless we're gonna use clang-format v10 or something
> 
> Good call, changed the .clang-format to v10 now.

Actually, clang-format v10 does not support `AlignOperands`. Are you sure that version is correct? Also we have been running clang-format v16 for all CLib actions and there hasn't been a single warning/error/problem. Reverted it back to v16.

**Comment by ThirdEyeSqueegee** [comment]
Sure here's one that's deprecated https://releases.llvm.org/16.0.0/tools/clang/docs/ClangFormatStyleOptions.html#constructorinitializerallononelineoroneperline

**Comment by powerof3** [comment]
Actually, setting the column limit to 0 should remove the limit

**Comment by gottyduke** [comment]
> Sure here's one that's deprecated

That's out of scope of this PR, feel free to submit another one that changes all deprecated rulesets **while** keeping the style the same as the past conventions, that'll be consistent for people to work with.

> Actually, setting the column limit to 0 should remove the limit

Changed it to the original.

**Pull request merged**
