### PR TITLE
feat!: replace vcpkg with CPM.cmake

### PR DESCRIPTION
**Pull request by ThirdEyeSqueegee**
Pros: 
- No vcpkg
- Can set spglog to use `std::format` so `fmt` doesn't get pulled in 
- Direct control of which versions to use for dependencies
- No vcpkg

Cons:
- Building takes ~1 second longer 
- ???

### CODE REVIEW

**Comment by nikitalita** [comment]
This is going to break so many workflows if you do this. If you must have cpm support, it should be IN ADDITION TO vcpkg support, not replacing it.

**Comment by ThirdEyeSqueegee** [comment]
vcpkg is shitty and I see dropping it as a good thing, I don't see how it would break anything if we stop using it for CLibSF. As for serving CLibSF, we can keep the vcpkg registry so users can continue to consume it that way

**Comment by alandtse** [comment]
Like it or not, vcpkg is a standard for us. It must be an option, not a breaking change.

**Comment by ThirdEyeSqueegee** [comment]
I don't think it's about like it or not, we should weigh the pros and cons and decide accordingly. The list I posted originally is a bit tongue-in-cheek but two big shortcomings of vcpkg are not being able to control build options for dependencies and the fact that it takes forever to update ports (xbyak is 3 versions behind on vcpkg at the time of writing). CPM has neither of these shortcomings. Even if vcpkg is a standard, it's a pretty awful one and I think CPM is a much better alternative--so why stick to vcpkg?

**Comment by alandtse** [comment]
I feel like you asked for comments and then ignored them. We are pointing out that it should not be a removal since it's a breaking change but adding an option should be fine. No one has said anything about whether one is superior or not, which is entirely what you are focused on with your responses. 

After a while maybe people will have migrated to cpm and then you'll have less pushback deprecating vcpkg.

**Comment by ThirdEyeSqueegee** [comment]
We merge breaking changes without any extra preparation all the time, don't see why there needs to be a cooldown period before doing the actual breaking in this particular case. Keeping vcpkg would sort of defeat the purpose of replacing it. I'm not trying to be dismissive, just trying to point out that there's solid reasons for getting rid of vcpkg.

**Pull request closed without merging**
