### PR TITLE
chore: chunky maintenance update

### PR DESCRIPTION
**Pull request by ThirdEyeSqueegee**
Changes:

- Add `[[nodiscard]]` where applicable
- Add `explicit` to converting constructors for `Version`, `Offset`, and `Relocation`
- Add `noexcept` to `Trampoline` move constructor
- ~~Add `SFSEPluginPreload` macro~~ #73 
- ~~Add `SFSEPluginVersion` macro to Interfaces.h~~ #73 
- Add `static` to `do_create()`
- ~~Add an overload for `PluginVersion` constructor which accepts a `REL::Version`~~ #73 
- ~~Add missing C++23 headers in PCH.h~~
- Add Singleton pattern class to PCH.h
- Apply `a_paramName` convention in a few places where it was missing
- Change explicit typing to `auto` in a few places
- Fix a variable name hiding a previous definition in Relocation.cpp
- Improve `SFSE::QueryInterface()` warning message
- ~~Improve const-correctness across the board~~
- Insert/remove newlines in a few places to improve readability
- Make `in_range()` `constexpr`
- Make `Trampoline` and `APIStorage` singletons
- Make some PCH.h functions `constexpr`
- Move hook helpers to API.h to avoid circular #includes
- ~~Remove `inline` from IAT.cpp template functions (redundant)~~
- ~~Remove PCH.cpp~~
- ~~Remove redundant value-initialization of some numeric and pointer type variables~~
  - ~~Pointers are value-initialized to `nullptr` by default and numeric types are value-initialized to `0` by default, specifying is redundant~~
- ~~Remove some unused #includes~~
- Remove Utilities.h
- ~~Small formatting tweak in Logger.h to make it more readable~~
- ~~clang-format:~~
  - ~~Enable `FixNamespaceComments`~~
  - ~~Add `RequiresClausePosition: OwnLine`~~
  - ~~Add `IndentRequiresClause: true`~~
  - ~~Change `SortIncludes` to `CaseInsensitive`~~

### CODE REVIEW

**Comment by gottyduke** [comment]
First, this is not a chore, you are introducing breaking changes with personal flavored coding styles. That trampoline change alone will already break many plugins, besides it makes zero sense to change it. 

Second, there's no releaseIndex in sfse. I intentionally removed GetReleaseIndex declaration for that reason. The implementation details didn't get removed because I'm not sure if one day sfse will add it back. You should really actually look at relevant code before making changes like that.
...
I'll stop counting here because there're so many things in this PR I don't even want to comment.

This is not a review, just a comment. CLibSF framework is already working and working fine, perhaps we should focus on adding actual RE work now.

**Comment by ThirdEyeSqueegee** [comment]
> I intentionally removed GetReleaseIndex declaration for that reason.

Would be nice to comment this kinda thing for clarity, will revert it. As for the GetTrampoline change I'll revert that as well since it's out of scope for this PR as you pointed out

**Comment by Qudix** [comment]
Need to remove the `SFSE/Utilities.h' include in `SFSE.h` otherwise it wont compile.

**Comment by ThirdEyeSqueegee** [comment]
> Need to remove the `SFSE/Utilities.h` include in `SFSE.h` otherwise it wont compile.

Good catch, it's still compiling just fine somehow lmao will remove it

**Comment by Qudix** [comment]
I think it would be a good idea for `SFSEPluginVersionData::PluginVersion` to also accept a `REL::Version` like the commonlib-ng. It can just be additional constructor.

**Comment by alandtse** [comment]
Style change should be done separately so not to clutter the diff. The main issue I see is you're using "chore" because you can't really categorize all the changes so you have a [giant catch-all](https://www.conventionalcommits.org/en/v1.0.0/#what-do-i-do-if-the-commit-conforms-to-more-than-one-of-the-commit-types). The fact you had "breaking changes" in a chore is also frightening. This also makes it harder to review.

That is all a sign you need to break up the changes so they do only 1 thing and they can be individually reverted. Honestly, I'd say choose one thing you want to cover with appropriate conventional commit and streamline this to only cover that.

**Comment by ThirdEyeSqueegee** [comment]
I hear you but I really don't think it's necessary (or fruitful) to enforce conventional commits to a T like that, the changes are interleaved across the affected files and splitting them up by scope would only make for a bunch of merge conflicts. I'll remove the reverted changes from the changelog so it isn't as cluttered. You're right in that adding breaking changes to a "chore" PR is silly, that was already made clear beforehand and has been reverted. Your point about large PRs being hard to review is well taken but I'll note that this one has a ~500 line diff, it isn't a particularly large PR by any means

**Pull request closed without merging**
