### PR TITLE
fix: `fmt` formatter for `REL::Version`

### PR DESCRIPTION
**Pull request by powerof3**

### CODE REVIEW

**Comment by qudix** [comment]
I think ThirdEyeSqueegee got the ball rolling to remove fmt for cmake users in #271

**Comment by ThirdEyeSqueegee** [comment]
@qudix yeah I'm pretty sure fmt isn't being pulled into the project anymore, we should just be able to nuke the fmt formatters

**Comment by qudix** [comment]
probably

**Comment by ThirdEyeSqueegee** [comment]
@powerof3 yeah if you use the custom port for spdlog in your project it won't pull fmt

**Comment by ThirdEyeSqueegee** [comment]
Merging but we should nuke the fmt formatters in the future

**Pull request merged**
