### PR TITLE
feat: add SKSEPluginLoad macro and getters for plugin name etc.

### PR DESCRIPTION
**Pull request by ThirdEyeSqueegee**

### CODE REVIEW

**Comment by gottyduke** [comment]
First, this is not "add", what you proposed it "replace" and it will break all existing plugins with current plugin API.
Second, you can't just copy them over, the plugin version struct is different. Your proposed version doesn't work.

**Comment by gottyduke** [comment]
Last to add: there's no `SFSEPlugin_Query` in SFSE.
Like I stated in #21 comments: please acutally **test the code locally** before trying to merge into upstream.

**Comment by gottyduke** [comment]
What's the point of these getters? All of its members are public, and those exact information is also set by the plugin author oneself. Why would they need to use a getter to retrieve something that's supposed to be set-once-for-all, by themselves? 

In current CLib plugin structure, the `SFSEPlugin_Version` is exported in `main.cpp`, meaning only that exact TU is able to access `SFSEPlugin_Version` instance.

At the end, even if a getter is useful or even required, a `std::string_view` among the char buffer is more suitable than `std::string` for avoiding unnecessary copy.

**Comment by ThirdEyeSqueegee** [comment]
While the getters may not be strictly necessary they're definitely in "can't hurt" territory; fixed the return type so there's no unnecessary copies

**Comment by gottyduke** [comment]
Ok, if you think the getters are good addition, consider adding proper `[[nodiscard]]` and `const` modifier for them, should any author ever uses the getter, they would not accidentally change them. Fool proof.

**Comment by ThirdEyeSqueegee** [comment]
Good call, done!

**Pull request merged**
