### PR TITLE
feat: add Conan support

### PR DESCRIPTION
**Pull request by ThirdEyeSqueegee**
Not tested for all presets but works for the ones I tested

EDIT: workflows failing bc the presets got renamed, will fix in a bit

### CODE REVIEW

**Review by jpstewart — COMMENTED** [review]
If possible I'd recommend using conan-cmake 2.x rather than using Conan as the primary driver of the build. This will clobber the CMakePresets and mess with what IDEs that integrate with CMake see.

There are complications to that. cmake-conan 2.x is in early development and doesn't work with cmake-generator-based dependencies. But I think it's worth testing if you can get that working (since fmt/spdlog at least are header-only they should be usable via Conan that way).

**Comment by ThirdEyeSqueegee** [comment]
Sounds good, will give that a go!

**Comment by gottyduke** [comment]
Do we... really... need... this...

**Comment by jpstewart** [comment]
> Do we... really... need... this...

Clib itself, IMO, only needs to build with either vcpkg or Conan but not both. However, providing both a vcpkg and Conan repository for downstream consumers is a good idea.

**Comment by ThirdEyeSqueegee** [comment]
> Do we... really... need... this...

I mean we didn't "need" Xmake or clang-cl support either

**Pull request closed without merging**
